### ISSUE TITLE
Cannot override SCSS variables reliably

### ISSUE THREAD

**Issue by kunalnagar** [taniarascia/primitive#10]
Hi there,

I installed `primitive-ui` via `npm` and included it in my `main.scss` file. I try to override the primary color variable and expect the link color to change automatically since it's based on the primary color. But it does not.

### Example

Here's how I use primitive in my own files:

```
// my own main.scss
@import "primitive-ui/src/scss/main";

@import "variables";
```

```
// my own variables.scss
$primary-color: red;
```

In the above example, the primary color has been set to red, and I would expect the link color to change to red as well, but it's still the default primary color supplied with primitive.

### The Fix
I've tested it and it can be fixed by adding `!default` values to the primitive variables. A similar approach is used in [Bootstrap](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L11-L22)

Please note that once you add `!default` values, the order of importing will change as well:

```
// my own main.scss
@import "variables";

@import "primitive-ui/src/scss/main";
```

If you'd like to read more about this approach, check [this article](https://thoughtbot.com/blog/sass-default) on Thoughtbot.

Finally, let me know what you think and I'll create a PR for it!

**Comment by taniarascia** [comment]
I really like this idea! I hadn't tested it out this way. Feel free to create a PR and I'll look it over. :) I do need to make some adjustments and update the documentation.

**Comment by kunalnagar** [comment]
@taniarascia I've created a PR. Let me know when you look it over! :)
