### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by spl** [taniarascia/primitive#15]
I was wondering if you would mind using `git` tags for versions and doing releases on GitHub. My reasons for this are:
1. [Notifications only for releases](https://help.github.com/en/articles/watching-and-unwatching-releases-for-a-repository): This is an admittedly selfish wish to reduce the amount of email I receive (e.g. by “watching” the repository) but still learn when updates are made.
2. Easily identifying the release commits and viewing the differences between them

**Comment by taniarascia** [comment]
I will do this going forward.
