### ISSUE TITLE
button and form default variables

### ISSUE THREAD

**Issue by tallsteve** [taniarascia/primitive#22]
Would you be willing to add the !default option to lines 145 & 146 in your variables setup? $buttons and $forms both required additional setup, and I found them to not follow the SCSS standard for overriding with a fallback.

https://github.com/taniarascia/primitive/blob/master/src/scss/base/_variables.scss

My current workaround required me to modify your code after the package was installed. Concern that I'll forget when I'm no longer working remote and pull a refresh from my package.json.

Thanks overall. Cheers.

**Comment by taniarascia** [comment]
Sure, I added it.
