### ISSUE TITLE
HTML 5 Elements Test link is broken

### ISSUE THREAD

**Issue by elizamarcum** [taniarascia/primitive#24]
That link was working just a few days ago, and I *loved* that HTML 5 Test page so much.  It was really illuminating to see all the frameworks compared!

After poking around a bit, it appears to me that you either deleted or made private the repo that used to be at https://github.com/taniarascia/html5-test. I was able to find a cached copy here: https://webcache.googleusercontent.com/search?q=cache:OaPkN3VjtHEJ:https://taniarascia.github.io/html5-test/&hl=en&gl=us&strip=0&vwsrc=1

P.S. Thanks for writing this excellent library!

**Comment by taniarascia** [comment]
Thanks! I did delete that repo. I added it back here: https://taniarascia.github.io/primitive/test.html
