### ISSUE TITLE
Error at Docs Website

### ISSUE THREAD

**Issue by Riguidix** [taniarascia/primitive#25]
I'm in Firefox 76.0.1 and i have recently find out that it duplicated it the entire web page

**It's duplicated**
[Primitive Docs or primitive/](https://taniarascia.github.io/primitive/)
![imagen](https://user-images.githubusercontent.com/24213002/82157636-f2ace480-983f-11ea-9fa6-98809f9fb11b.png)

**Normal page**
[Index of Primitive Docs or primitive/index.html](https://taniarascia.github.io/primitive/index.html)
![imagen](https://user-images.githubusercontent.com/24213002/82157680-3acc0700-9840-11ea-9494-a38805dfa86c.png)

**Comment by ovieu** [comment]
Hi @Riguidix, do you still have this problem? How can one reproduce it? 
As a fix, I would suggest you start with checking the third party extensions installed in your browser.

**Comment by Riguidix** [comment]
Currently just opening the [Primitive UI](https://taniarascia.github.io/primitive/) from this link `https://taniarascia.github.io/primitive/` cause the malfunction. Trying the extensions part, but isn't the problem

![imagen](https://user-images.githubusercontent.com/24213002/82977063-fa862a80-9f9d-11ea-93a2-3ce965999cc2.png)
Even w/View Source it's shows 2 head's and 2 body's

PS: Sorry for my bad English

EDIT: The important thing it's that only happens at Firefox, tested at Chrome and no errors
