### ISSUE TITLE
Primitive in react

### ISSUE THREAD

**Issue by mchun** [taniarascia/primitive#6]
Hi Tania,
thanks for creating primitive!
When I try to integrate it with react, I encounter a strange problem.
The spacing between buttons are missing and I can't figure out the problem.
Is that the problem of react?

in html:

```
    <div class="container">
       <button>Submit</button>      
       <button>Reset</button>    
    </div>
    <div id="root"></div>
```

in js:

```
class App extends Component {
  render() {
    return (
      <div className="container">
       <button>Submit</button>      
       <button>Reset</button>            
      </div>
    );
  }
}

ReactDOM.render(<App/>, document.getElementById('root'));
```

![screen shot 2018-06-28 at 5 39 57 pm](https://user-images.githubusercontent.com/7677094/42026696-6ce8ab36-7afa-11e8-8e82-c42f732c6687.png)

**Comment by taniarascia** [comment]
This probably just has to do with React not rendering white space in the DOM. You’ll just have to adjust the spacing on the buttons accordingly.

**Comment by mchun** [comment]
Thanks for the reply, I added margins to buttons manually to solve the problem.
