### ISSUE TITLE
Remove gulp

### ISSUE THREAD

**Issue by vdeville** [taniarascia/primitive#9]
Hello,
Why you remove gulp ?
If you want, I can again integrate Gulpfile.js with the newest version of gulp (4.0).
I use primitive with my custom gulp scripts.
Tell me if you are interest.
Thanks

**Comment by taniarascia** [comment]
Do you still do this? I wanted to make Primitive not rely on Gulp, but I'm not sure how to add autoprefixing as well to the npm script.

**Comment by vdeville** [comment]
Hello, yes here a sample script i use:
```javascript
'use strict';

const {src, dest} = require('gulp');
const sass = require('gulp-sass');
const rename = require('gulp-rename');
const cssnano = require('gulp-cssnano');
const autoprefixer = require('gulp-autoprefixer');

function css() {
    return src('./src/scss/main.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }))
        .pipe(cssnano({
            zindex: false
        }))
        .pipe(rename((path) => {
            path.basename += ".min";
        }))
        .pipe(dest('../../web/css/'))
}

exports.css = css;
exports.default = css;
```
packages.json:
```json
  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-sass": "^4.0.2",
    "gulp-autoprefixer": "^4.1.0",
    "gulp-cssnano": "^2.1.3"
  }
```
Thanks

**Comment by ahmadrasyidsalim** [comment]
> Do you still do this? I wanted to make Primitive not rely on Gulp, but I'm not sure how to add autoprefixing as well to the npm script.

I'm curious, I mean how about the ```watch``` flag on ```node-sass``` and ```postcss-cli```? Or can we prefix the SCSS before execute node-sass to traspile it to CSS output?

**Comment by taniarascia** [comment]
Added autoprefixer to the build command.
